### ISSUE TITLE
How to debug oAuth on device

### ISSUE THREAD

**Issue by pors** [meteor/accounts#11]
I am using a library that relies on accounts-oauth and all works fine, except that on an iPhone app (via TestFlight) the popup window doesn't close automatically after the callback/redirect.

See https://github.com/xinranxiao/meteor-accounts-spotify/issues/5

It does work fine in the ios emulator and also with ios-device. I have no idea how to debug this on a deploy via TestFlight. Any tips are much appreciated.

**Comment by hwillson** [comment]
Hi @pors - issues in this repo are intended to represent either bugs with the accounts packages, or feature requests. Requests for help like this are much better suited on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor).

That being said, now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

If you feel like there is a bug lurking here somewhere, please consider opening a new issue in the [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

Closing - thanks!
