### ISSUE TITLE
Email verification token expiration

### ISSUE THREAD

**Issue by cbdotguru** [meteor/accounts#12]
I believe not having tokens expire after a certain period of is a security gap. I found no functionality available to do this even though token objects are stored with a timestamp, so I'd like to suggest having something available as follows:

//users can configure the timeout in minutes to expiration
var emailTokenTime = Accounts.configure.verifyEmailTokenExpiration;

Meteor.methods({verifyEmail: function (token, emailTokenTime) {
  var self = this;
  return Accounts._loginMethod(
    self,
    "verifyEmail",
    arguments,
    "password",
    function () {
      let timeNow = new Date();
      check(token, String);
      let ett = emailTokenTime;
     //check if the config is set and, if it is, it's the appropriate type
      if (!!ett) {
        check(ett, Number);
      }
      var user = Meteor.users.findOne(
        {'services.email.verificationTokens.token': token});
      if (!user)
        throw new Meteor.Error(403, "Verify email link expired");

```
  var tokenRecord = _.find(user.services.email.verificationTokens,
                           function (t) {
                             return t.token == token;
                           });
  if (!tokenRecord)
    return {
      userId: user._id,
      error: new Meteor.Error(403, "Verify email link expired")
    };

  var emailsRecord = _.find(user.emails, function (e) {
    return e.address == tokenRecord.address;
  });
  if (!emailsRecord)
    return {
      userId: user._id,
      error: new Meteor.Error(403, "Verify email link is for unknown address")
    };
 //if the config is set run the time check
 if (!!ett) {
   let tokenTime = tokenRecord.when.valueOf();
   let functionTime = timeNow.valueOf();
   let expMinutes = ett*60000;
   let expired = (( functionTime - tokenTime) > expMinutes);
   //if the difference between token creation and now is greater 
   //than the minutes set, pull the record and return an error.
   if (expired) {
     Meteor.users.update(
       {_id: user._id,
        'emails.address': tokenRecord.address},
       {$pull: {'services.email.verificationTokens': {address: tokenRecord.address}}});

     return {
       userId: user._id,
       error: new Meteor.Error(403, "Verify email link expired")
     };
   }
 }
  // By including the address in the query, we can use 'emails.$' in the
  // modifier to get a reference to the specific object in the emails
  // array. See
  // http://www.mongodb.org/display/DOCS/Updating/#Updating-The%24positionaloperator)
  // http://www.mongodb.org/display/DOCS/Updating#Updating-%24pull
  Meteor.users.update(
    {_id: user._id,
     'emails.address': tokenRecord.address},
    {$set: {'emails.$.verified': true},
     $pull: {'services.email.verificationTokens': {address: tokenRecord.address}}});

  return {userId: user._id};
}
```

  );
}});

My first post, hope it's useful.

**Comment by javascriptlove** [comment]
There is expired token removal here https://github.com/meteor/accounts/blob/77b6084c0bd24129c1e7a6d703d9effddaceadcb/packages/accounts-base/accounts_server.js#L1077
And it is run every 10 minutes if i understand correctly

Not an issue

**Comment by cbdotguru** [comment]
That link references tokens used to resume a session. My issue references email verification tokens sent to a users' unverified email. If someone were to gain unauthorized access to an email, the first thing done would be to scan for verification links and gain access to those accounts.

**Comment by javascriptlove** [comment]
Aha, i see, i think as a temporary workaround it might be ok to have a setInterval similar to the session tokens. Something like every hour, and using Meteor.users.update() to remove token in emails with date less than current date minus your expiration timeout. But I +1 for having it somewhere in core

**Comment by cbdotguru** [comment]
It's been a while since I wrote this but I did end up rolling my own with something similar I suggested here. Rather than scanning the database with a cron job though, it just does the check when the token is being used and, if it's too old, the token is quietly removed at that time and an error is thrown.

**Comment by hwillson** [comment]
Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

If you feel like this feature request should still be addressed, please consider opening a new issue in the [`meteor/meteor`](https://github.com/meteor/meteor) repo. Thanks!

**Comment by Melli2345** [comment]
wrzmp7672@gemailu.com
