### ISSUE TITLE
Facebook auth doesn't work on anything else than Chrome with IDN callbacks

### ISSUE THREAD

**Issue by pzduniak** [meteor/accounts#13]
Just try to log in on https://ućladder.pl/ - you will see the error.

**Comment by pzduniak** [comment]
window.location must be transformed to punycode

**Comment by hwillson** [comment]
Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

If you feel like this is still an issue, please consider opening a new issue in the [`meteor/meteor`](https://github.com/meteor/meteor) repo.
