### ISSUE TITLE
Verify Email function does not remove tokens for email in a different case(upper or lower)

### ISSUE THREAD

**Issue by addynaik** [meteor/accounts#17]
Lets say user adds an email into his account as `abc@mail.com`. then adds the same email as `ABC@mail.com`. when he gets the second verification email and clicks it, it removes the token records for emails sent to ABC@mail.com but not abc@mail.com. 

i think the issue is this line - 

https://github.com/meteor/accounts/blob/master/packages/accounts-password/password_server.js#L838

we should instead - 

    $pull: {'services.email.verificationTokens': {address: { $regex : new RegExp('^' + Meteor._escapeRegExp(tokenRecord.address) + '$', 'i') }}}});

**Comment by hwillson** [comment]
Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

I've migrated this issue over to meteor/meteor#8532. Closing here - thanks!
