### ISSUE TITLE
Meteor.loginWithPassword does't respond under ipv6 root_url.

### ISSUE THREAD

**Issue by Eagles2F** [meteor/accounts#19]
Hi,
I've been working with angular-meteor and meteor backend for my cross-platform mobile project.
The IOS app store rejected my submission due to well-known ipv6-only network issue.

I have successfully reproduced the bug on my mac. Here is what I have done:

set up a NAT64/DNS64 local network following this guidefrom apple.
start up a meteor server with this cmd: ROOT_URL="http://2001:2::aab1:e:c6ff:feac:2264:3000" meteor run
changed my angular-meteor DDP connection URL using this cmd: window.__meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL = 'http://2001:2::aab1:e:c6ff:feac:2264:3000';
run my angular-meteor project using ionic cmd ionic serve
After the last 4 steps, I could successfully open my site. The websocket connection seems ok to me. no error log showed up. However, when I came to my login page. The code gets stuck here: Meteor.loginWithPassword(username, password, Angular.bind(this, function(err) { if (err) { console.log('Login error - ', err); failure(err); } else { console.log('Login success'); o.setSession(username, password); success(); } }));

This Meteor.loginWithPassword method never replied.

I'm wondering someone who knows this accounts package or meteor could help me.
My end goal is to make this login work under ipv6.

**Comment by hwillson** [comment]
Hi @Eagles2F - issues in this repo are intended to represent either bugs with the accounts packages, or feature requests. Requests for help like this are much better suited on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor).

That being said, now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

If you feel like there is a IPv6 bug within the accounts packages, please consider opening a new issue in the [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

Closing - thanks!
