### ISSUE TITLE
loginWithPassword username enumeration vulnerability

### ISSUE THREAD

**Issue by samgurtman-zz** [meteor/accounts#20]
LoginWithPassword method can results in error states that reveal whether a given username or email exists in the system.

If a username exists it will return "“Incorrect password [403]” if the password provided is incorrect." if the password is incorrect.

I would like to see this configurable.

**Comment by abernix** [comment]
You'll probably be interested in https://github.com/meteor/meteor/pull/8520, which directly tries to address your concern.

However, this repository itself actually is not the active "Accounts" package, which is still a part of the main Meteor repo.  This branch was an attempt to extract the accounts packages.  Further issues with the active `accounts-*` packages should go on the [main Meteor repo](https://github.com/meteor/meteor/).
