### ISSUE TITLE
Need several facebook,g+ and twitter configs

### ISSUE THREAD

**Issue by humbertocruz** [meteor/accounts#24]
Hello,

I'm building a App Builder and I need to configure the login for facebook, etc for several clientes ( each one with his own app ). But this is done on the same application. I made a Social collection, save the appID and secret for each client. I do not think I can use ServiceConfiguration for this... each client will try to login.
I thinking to clone the ServiceConfiguration, add the "appId" on each config and restore it wihtin this appId information.

any help ?
thanks

**Comment by hwillson** [comment]
Hi @humbertocruz - issues in this repo are intended to represent either bugs with the accounts packages, or feature requests. Requests for help like this are much better suited on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor).

That being said, now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. Closing - thanks!
