### ISSUE TITLE
Unexpected logout() behavior in deployed Meteor app

### ISSUE THREAD

**Issue by tgoldenberg** [meteor/accounts#6]
So I cannot reproduce this issue locally, but in our deployed Meteor app, if a user logs in and then immediately scrolls, they get logged out. There is no code that would make this happen, as `Meteor.logout()` is called only when the user clicks the logout button. Any idea on why this might be happening? This is a pretty big concern

**Comment by jedwards1211** [comment]
I'm also seeing random spontaneous logouts in a deployed Meteor app.  It seems potentially related to intermittent network connection failures because at one point all clients on one of our customer's sites got logged out at once.  Is there anything in the Meteor codebase that can cause a spontaneous logout?

**Comment by hwillson** [comment]
Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

If you feel like this is still an issue, please consider opening a new issue in the [`meteor/meteor`](https://github.com/meteor/meteor) repo.
