### ISSUE TITLE
Any plan for this repo in the future?

### ISSUE THREAD

**Issue by yubozhao** [meteor/accounts#8]
I would love to help contribute with linkAccounts and have this working with Apollo.  Would love to have outline of what's next.

**Comment by nickredmark** [comment]
+1

**Comment by NicholasEli** [comment]
+1

**Comment by hwillson** [comment]
This repo will not be maintained moving forward. Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. Thanks!
